### ISSUE TITLE
No teensies in boards.txt

### ISSUE THREAD

**Issue by zeldin** [PaulStoffregen/Arduino-1.6.9-Teensyduino#1]
Hi.

This repo is supposed to contain the changes made by Teensyduino, but there are no Teensy
boards in the boards.txt file?

**Comment by PaulStoffregen** [comment]
This repo is the Java source changes.

**Comment by PaulStoffregen** [comment]
Oh, looks like the readme edit could be clearer about that detail... will fix in a moment.

**Comment by PaulStoffregen** [comment]
Sorry about the confusion.  Hopefully this will make it clearer in the future.  https://github.com/PaulStoffregen/Arduino-1.6.9-Teensyduino/commit/64bf10b6bc15a5b427ec779f56d5b847cc945320

**Comment by zeldin** [comment]
Thanks.  Although maybe a pointer to where the non-Java stuff is would make it even more helpful?  (I'm trying to make a Gentoo ebuild installing Teensyduino from sources.)
